### ISSUE TITLE
No issue, only thankfulness (feel free to close)

### ISSUE THREAD

**Issue by mdio** [dokufreaks/dokuwiki-plugin-davcal#5]
Hi! I just wanted to express my thankfulness for your efforts to make this plugin work again and compatible with the latest Dokuwiki version.
I'm using this in a wiki for a school and the calendar was one of the best features in my opinion.
With this parents (like me) could easily integrate the school events into the rest of their calendars on mobile devices or desktop calender applications.
When the UI on the wiki broke, we were no longer able to change or add new calendar entries.
With the new school year getting closer and closer, this was becoming a major problem as the new year comes with new appointments obviously.
While the rest of the people will not even notice that there was a problem (as the ics export still worked) but for me you absolutely saved the day.
Thank you so much!

**Comment by Klap-in** [comment]
Thanks for the kind words!
